IDE/Lab#4/blog/config/routes.rb
Rails.application.routes.draw do
   get 'welcome/index'

    resources :articles
 
   root 'articles#me'

end

IDE/Lab#4/blog/app/models/article.rb
class Article < ActiveRecord::Base
end

IDE/Lab#4/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

IDE/Lab#4/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController::Base

def me
end

end

IDE/Lab#4/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

IDE/Lab#4/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

IDE/Lab#4/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

IDE/Lab#4/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

IDE/Lab#4/blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %> 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

IDE/Lab#4/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %> 
 <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

IDE/Lab#4/blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>

IDE/Lab#4/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

IDE/Lab#4/blog/app/views/welcome/me.html.erb
<h1>Leahu Luminita - FAF - 121</h1>